export const initialStaffValues = {

	id: '',
	TypeSalary: '',
	valueperHour: 0,
	baseSalary: 0,
	profession: '',
	id_BaseSalary: '',
	IdType: '',
	Names: '',
	SureNames: '',
	Gender: '',
	email: '',
	Phone: '',
	occupation: '',
	DateofBirth: '',
	DepartamentBirth: '',
	MunicipeBirth: '',
	neighborhood: '',
	Address: '',
	EPS: '',
	img: '',
	role: '',
}